
rdpso:
  c1: 1.5
  c2: 1.5 
  max_velocity: 0.04
  scenario_size: 10.0
  control_frequency: 20 
  convergence_threshold: 0.1 
 
  obstacle_detection_range: 2.0
  avoidance_threshold: 1.0 
  avoidance_gain: 0.5 
  cluster_distance: 0.3
  
  fitness_noise_sigma: 0.01
  
  marker_lifetime: 0.5
  obstacle_height: 0.5
  
  communication_timeout: 1.0
  max_comm_failures: 5
